Mulig løsning på trege fetch
Kaffe-diem/frontend pull request #23
Opened 2024-10-21 16:56 UTC by CarlAugust

Årsaken til den sakte hastigheten når vi skulle laste data på nettsiden var rett og slett at vi lagde en ny PB instans når vi skulle fetche i +page.svelte i /drinks. Løsningen var å lagre pb fra hoooks.server.ts i Locals. Med dette kunne jeg bare ta den verdien fra locals når jeg skulle hente data i +page.server.ts.

2024-10-21 17:04 UTC, LilleAila requested changes

2024-10-21 17:08 UTC, LilleAila commented
Nå har vi to ulike instanser av pb: en i frontend under `$lib/stores/authStore.ts`, og en i backend under `hooks.server.ts`. Den eneste mulige løsningen jeg kommer på som unngår dette blir å kun gjøre pb-requests i backend, gjennom en REST-api, eller helst `+page.server.ts` slik som du gjorde. For nå mener jeg det er greit å beholde det som det her, og hvis det skal endres blir det i så fall en annen PR.

2024-10-21 17:16 UTC, CarlAugust commented
Er ikke pb fra hooks.server.ts den samme som den i $lib/stores/authStore.ts, siden det er der vi importerer den fra? Eller lager det en duplikasjon?

2024-10-21 17:16 UTC, LilleAila commented on src/routes/drinks/+page.svelte
> +    const pb = new PocketBase('https://your-pocketbase-url.com');
Forøvrig mener jeg også at å subscribe ikke er nødvendig i dette tilfellet, da det er usannsynlig at menyen endres så ofte at det skjer mens en bruker holder på å lese den / å bestille

2024-10-21 17:27 UTC, CarlAugust commented on src/hooks.server.ts
Vet ikke helt hva du mente, men flyttet event.locals.pb = pb, til etter redirect hvis man ikke er autentisert.

2024-10-21 18:03 UTC, kluvin commented on src/routes/drinks/+page.svelte
> +    const pb = new PocketBase('https://your-pocketbase-url.com');
Det vil ikke være nødvendig å subscribe på /drinks nei!

2024-10-21 18:19 UTC, kluvin commented
Jeg er ganske skeptisk på å ha server-side logikk: https://github.com/pocketbase/pocketbase/discussions/5313

Det fins noen få regler:

> It is safe to have a single PocketBase JS SDK instance only when used:

>    on the client-side (ex. browser)
>   on the server-side when in "serverless"/worker/lambda/etc. mode that essentially init a new js process with each request and destroy it after serving the response
 >   on the server-side when used as admin
    
  Her er det mulig å bruke en server-side instans som admin (for denne routen), men jeg er usikker på om det er problematisk med innblanding av auth.

2024-10-21 19:26 UTC, CarlAugust commented
Kan du forklare hvordan dette hadde fungert. med global PB på client siden?

2024-10-21 19:27 UTC, CarlAugust commented
Jeg har også prøvd å lese litt rundt omkring, og i følge chatgpt, som kan være en litt iffy kilde å bruke men så så. Så er server.js moduler til svelte stateless. Jeg vet ikke hvordan det fungerer i tilfelle av pocketbase da.

2024-10-21 19:29 UTC, LilleAila commented
> Kan du forklare hvordan dette hadde fungert. med global PB på client siden?

Så vidt jeg vet gjør den førnevnte `authStore.ts` dette her, men det kan hente jeg tenker feil.

2024-10-21 19:37 UTC, CarlAugust commented
> > Kan du forklare hvordan dette hadde fungert. med global PB på client siden?
> 
> Så vidt jeg vet gjør den førnevnte `authStore.ts` dette her, men det kan hente jeg tenker feil.

Da er det vell ett problem at jeg har det delt mellom +page.server.ts og klient siden da? Siden det blir samme instans i backend og client?

Men, jeg lurer på om som oftest når en client kobler til en server at de får en egen instans av all server side koden, altså at det dupliserer server socketen for hver bruker og derfor så kommer ikke pocketbase instansene til å mikse opp mellom brukere. Hvis det var det som er det mulgense problemet?

2024-10-21 19:42 UTC, CarlAugust commented
Men å beholde PB instansen på client siden ekslivt, ville det bare vært page.svelte filene?

2024-10-21 19:56 UTC, kluvin commented
1. Hvis det var det som er det mulgense problemet? Korrekt
2. Men å beholde PB instansen på client siden eksklusivt, ville det bare vært page.svelte filene? Korrekt

Jeg implementerte /account https://github.com/Kaffe-diem/frontend/pull/25 som har favoritter og slikt

Denne siden bør jo absolutt ikke kunne lese ting som brukeren har registret på seg.

Så lenge man kan sitte en API rule som begrenser hva vi kan hente her, er det bra.

Problemet her kunne jo vært tilfelle at det er en PB instans i en .server.js modul, som blir autentisert som en bruker A. Men ved en senere etterspørsel kommer data fra bruker B.

Hvis modulen er stateless, går dette jo fint. Jeg er bekymret siden dokumentasjonen til pocketbase spesifikt poker på dette problemet.

2024-10-21 20:01 UTC, LilleAila commented
> 1. Hvis det var det som er det mulgense problemet? Korrekt
> 2. Men å beholde PB instansen på client siden eksklusivt, ville det bare vært page.svelte filene? Korrekt
> 
> Jeg implementerte /account #25 som har favoritter og slikt
> 
> Denne siden bør jo absolutt ikke kunne lese ting som brukeren har registret på seg.
> 
> Så lenge man kan sitte en API rule som begrenser hva vi kan hente her, er det bra.
> 
> Problemet her kunne jo vært tilfelle at det er en PB instans i en .server.js modul, som blir autentisert som en bruker A. Men ved en senere etterspørsel kommer data fra bruker B.
> 
> Hvis modulen er stateless, går dette jo fint. Jeg er bekymret siden dokumentasjonen til pocketbase spesifikt poker på dette problemet.

Alternativt, hvis vi vil være 100% sikker på å unngå slike konflikter, kan vi bruke en uautentisert instance på server-siden, mens client-siden er autentisert. Da vil den kun kunne lese f. eks drinks, men ikke skrive noe eller lese noe som krever auth

2024-10-21 20:06 UTC, kluvin commented
@LilleAila i svelte server hooks ja, det kan gå. Det bør også gå å ha en autentisert admin bruker på en edge funksjon, men da må vi være sikker på at vi får en runtime per http-execution

2024-10-21 20:10 UTC, LilleAila commented
> @LilleAila i svelte server hooks ja, det kan gå. Det bør også gå å ha en autentisert admin bruker på en edge funksjon, men da må vi være sikker på at vi får en runtime per http-execution

Tror vi kan unngå hooks helt, da denne pb instancen kun må initializes en gang og kan deles mellom *alle* users og requests, siden den er read-only. Noe som `export const pb = new PocketBase(PUBLIC_POCKETBASE_URL)` i en egen fil som importeres hvert sted man ellers ville laget en ny (på server side).

2024-10-22 09:10 UTC, CarlAugust commented
Jeg flytter alt til +page.svelte filen, jeg er litt usikker på hvordan Locals fungerer da, er det serverside eller client side?

2024-10-22 14:30 UTC, closed without merging