Implement /account, first user specific page
Kaffe-diem/frontend pull request #25
Opened 2024-10-21 19:50 UTC by kluvin

2024-10-22 11:12 UTC, CarlAugust commented
Jeg fikset ett problem med at det ikke ville loade, Drink fra $lib/Drink.svelte fantes ikke, hvis noen vi lage denne kan de.

2024-10-22 11:15 UTC, LilleAila commented
> Denne regelen skal garantere at `auth.user` ikke kan lese en `order_drink` som ikke er lagt til i user.favorites

Kunne du forklart hvordan systemet med favoritter og order_drink fungerer? Jeg forstår ikke helt hva du mente med det


Jeg synes også at kanskje dette burde være en annen route enn `/`, heller noe som `/menu`? Vi burde kanskje hatt noe litt annet enn å gå direkte til menyen, for eksempel som i #20

2024-10-22 11:43 UTC, kluvin commented
> Kunne du forklart hvordan systemet med favoritter og order_drink fungerer? Jeg forstår ikke helt hva du mente med det

Se kun på `order_drink` som er en sammling hvilket inneholder unike "drinker" laget per bestilling. Disse er tilknyttet en ordre, som er tilknyttet en bruker. Derfor er en drink tilknyttet en bruker. Bare en bruker bør derfor ha tilgang til en vilkårlig drink.

Pocketbase har API regler for filtrering og adgangskontroll, disse må brukes, og vil representere en del av business logikken i systemet.

2024-10-22 11:45 UTC, LilleAila commented
> @LilleAila beklager, jeg så ikke bilde i den PRn!
> 
> Jeg tenker jo det absolutt første en bruker vil gjøre den første, andre, og tredje gangen de går inn på siden er å bestille, med minst mulig klikk. Jeg tenker så lite som to-tre klikk for 80% av bestillinger, dvs i stor grad de uten ekstravalg (men selv her kan favoritter brukes).
> 
> Hva er formålet med å ha reviews på forsiden, og hvordan tjener dette brukeropplevelsen?
> 
> Jeg ville nedprioritert reviews, kaffe-diem har alt et etablert rykte som er positivt, og er i grunn og bunn et statlig eid monopol.

Reviews er ikke viktig, jeg bare lagde en enkel versjon fordi jeg ville ha noe å fylle strtsiden med, så det er egentlig null grunn til å ha det på forsiden utenom å midlertidig fylle den med noe. Kanskje man heller kunne vist et utvalg fra menyen eller noe slikt?

2024-10-22 12:05 UTC, kluvin commented
> vist et utvalg fra menyen eller noe slikt?

For å spille på dette kunne vi tagget noen ting som populære

2024-10-22 12:15 UTC, kluvin commented
@CarlAugust tusen takk! du redda meg!

2024-10-22 12:18 UTC, LilleAila commented
> > vist et utvalg fra menyen eller noe slikt?
> 
> For å spille på dette kunne vi tagget noen ting som populære?

Jeg tenker vi kan lage en form for dashboard for admins (de som jobber i kaffe diem), der de kan redigere kategorier, produkter og da også merke hva som skal vises på forsiden eller ikke. Da ville vi trengt noe som en boolean for hver user som sier om de er admin eller ikke, slik at de får tilgang til de sidene de trenger og har write-access i db ved hjelp av pb-regler.

2024-10-22 16:22 UTC, LilleAila commented
Formatert kode til å passe med #11. Flyttet `/+page.svelte` til et annet sted, siden `origin/main` har en annen route der. Kan endres til hvordan du synes det passer best.

2024-10-22 17:56 UTC, kluvin commented
@LilleAila 

Intensjonen var å lagre favoritter og ordrehistorikk inntil i `/account` som jeg for øvrig tolker som "min side", inntil videre, ettersom jeg ikke ser behov for å lage en rute for disse to.

Det er emne som kan tas opp i felleskap, derimot. Jeg ser grunn til å vise favoritter og historiske kjøp på bestillingssiden, som jeg hittil har sett for meg er `/`.

Vi har all mulighet i verden til å gjøre mange dårlige valg i dag og fikse på dem i morgen.

2024-10-22 17:59 UTC, kluvin commented
@IldenH 

Vi lagrer denne dataen i `order_drinks` og kan kjøre aggregates på den, for å finne ut dette samt om for eksempel mocca blir solgt mer av på fredager, eller mandager. Hvis vi har 1 million records der tar en query for å samle data, så tar den forholdsvis veldig kort tid.

Inntil videre eksisterer ikke denne dataen, og så vil den være ustabil, så ser dette som en oppfordring til å hardkode i utgangspunktet.

2024-10-22 18:55 UTC, LilleAila commented
> Intensjonen var å lagre favoritter og ordrehistorikk inntil i `/account` som jeg for øvrig tolker som "min side", inntil videre, ettersom jeg ikke ser behov for å lage en rute for disse to.

Dette synes jeg passer, det var originalt dette jeg hadde tenkt den skulle brukes til.

> Det er emne som kan tas opp i felleskap, derimot. Jeg ser grunn til å vise favoritter og historiske kjøp på bestillingssiden, som jeg hittil har sett for meg er `/`.
> 
> Vi har all mulighet i verden til å gjøre mange dårlige valg i dag og fikse på dem i morgen.

Det er jeg enig i; jeg synes det passer med bestilling på `/`, men flyttet den midlertidig for å unngå merge-konflikter når jeg merget main til denne branchen.

2024-10-22 19:28 UTC, kluvin commented
Mottatt. Vi kan flytte alt på sikt, rent organisasjonsmessig. Jeg vet ikke hvordan det vil se ut med reviews og det som er på forsiden nå. Jeg tenker denne PR er klar til merge, dog det gjenstår en del arbeid.

2024-10-23 16:59 UTC, LilleAila requested changes

2024-10-23 17:11 UTC, kluvin commented on src/lib/Drink.svelte
> +  const purchased_cup = pb.authStore.model?.purchased_cup;
Det var det jeg tenkte på også. En kopp kan være i inventar, men denne regner jeg som eierskap over kopp, og om det skal være standardvalg. Om folk kjøper flere kopper, har dem kjøpt minst en kopp.

2024-10-23 17:13 UTC, kluvin commented on src/routes/drinks/+page.svelte
> +    <ul class="grid grid-cols-3 gap-16">
tenker noe minmaxing her er optimalt i fremtiden, men dette funker for nå

2024-10-23 17:16 UTC, kluvin commented on src/routes/drinks/+page.svelte
> +  <section>
Jeg valgte bevisst å ikke faktorisere dette inntil vi vet at det skal være slikt. Jeg mange snarveier med intensjon.

2024-10-23 17:16 UTC, kluvin commented on src/routes/drinks/+page.svelte
> +    const drinks = await pb.collection("drinks").getFullList(100, {
👍 OK

2024-10-23 17:17 UTC, kluvin commented on src/routes/account/+page.svelte
> +      {pb.authStore.model?.name.split(" ")[0].toUpperCase()} ELSKER
Jeg eksperimenterer med det visuelle, vi bør gjennomgå visuell identitet helt seperat for utviklingen. Men jeg forstår at dette var et unikt valg.

2024-10-23 17:18 UTC, kluvin commented on src/lib/Drink.svelte
> +      <div class="flex space-y-2">
Jeg er klar over det, er ikke sikker på om det skal være et form som dette enda. Det praktisk nødvendig  for å kode inn bestill knappen, jeg tenker visuelt design kan spares til litt frem i tid.

2024-10-23 17:29 UTC, kluvin commented
@LilleAila Jeg foreslår at vi fokuserer på alt av UI/UX samt a11y inntil vi har lansert den mest enkle og nødvendige funksjonaliteten.

Selv er jeg den mest pedantiske når det gjelder brukeropplevelser, men vi må ha fokus på en ting av gangen. Det er helt reelle odds for at jeg kaster vekk 90% av koden her neste uke.

Av ting som er nevnt, ser jeg kun behov for å fikse server loading, gitt vi har nå valgt å gjøre dette globalt, samt den 500 tingen du ser.

Hva tenker du?

2024-10-23 18:47 UTC, CarlAugust commented
Er tilfelle at vi kaster vekk 90% av koden hvis vi velger å bruke noe annet enn pocketbase?

2024-10-23 21:18 UTC, kluvin commented
> Er tilfelle at vi kaster vekk 90% av koden hvis vi velger å bruke noe annet enn pocketbase?

Egentlig UI, men også pocketbase. Hvis vi kaster bort pocketbase, har vi lært hvordan datamodellen skal se ut via iterasjon gjennom pocketbase, og det er verdt det.

Det som er fint med pocketbase er at den bruker sqlite, som er portabelt.

Det eneste jeg fokuserer på nå er hvordan datamodellen, altså databasen, og noe av arkitekturen, skal se ut. Alt annet er konsekvent.

2024-10-24 06:46 UTC, didriksn commented
"Logg Ut" knappen bør være i "Min Bruker" menyen, istedenfor å være oppe i høyre hele tiden.

2024-10-25 16:41 UTC, merged